### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jonkirkham-arm** [Praqma/MonKit#1]
Hi, 

Is it possible for you to add a license to this work (ideally something liberal MIT, BSD)?
This would make it far easier to use in a commercial environment.

Thanks,
Jon.

**Comment by MadsNielsen** [comment]
Added a LICENSE.md file

**Comment by jonkirkham-arm** [comment]
Thanks!

**Comment by MadsNielsen** [comment]
You're welcome. I'm curious to know how you're using MonKit? Would you allow me to contact you via email and get your story? We're very interested in gathering information as to how people use this, and why.
